import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Main from '../components/Main'
import Header from '../components/Header'


const Home: NextPage = () => {
  return (
    <div className={styles.container} data-theme="dark">
      <Head>
        <title>Los Pollos Hermanos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hackathon lohgo.png" />
      </Head>
      <Header />
      <Main />
    </div>
  )
}

export default Home
